configserver:
    name: Yuan Config Center
    status: Yuanscore Registry Service

jhipster:
    security:
        authentication:
            jwt:
                secret: my-secret-key-which-should-be-changed-in-production-and-be-base64-encoded
